---
title: Clearwater Healing House
baseurl: ''
url: http://clearwaterhealinghouse.org
markdown: kramdown
theme: aegean

exclude:
- Gemfile
- Gemfile.lock

collections:
  carousel:
    caption: My Caption

# defaults:
#   -
#     scope:
#       path:
#     values:
#       caption: 
