title: Clearwater Healing House
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clearwaterhealinghouse.org"

# Build settings
markdown: kramdown
theme: aegean
exclude:
  - Gemfile
  - Gemfile.lock
